### ISSUE TITLE
Drush patch file on new setup

### ISSUE THREAD

**Issue by kevincrafts** [CuBoulder/express_local#49]
fatal: [express.local]: FAILED! => {"changed": true, "cmd": ["drush", "dl", "registry_rebuild", "-y"], "delta": "0:00:00.514765", "end": "2016-12-22 16:03:55.532026", "failed": true, "rc": 1, "start": "2016-12-22 16:03:55.017261", "stderr": "Project registry_rebuild (7.x-2.4) downloaded to                     \u001b[1;32;40m\u001b[1m[success]\u001b[0m\n/home/osr_web_deploy/.drush/registry_rebuild.\nfile_get_contents(/data/code/profiles/express/express-current/patches.make):\u001b[1;33;40m\u001b[1m[warning]\u001b[0m\nfailed to open stream: No such file or directory\nmake.utilities.inc:480\nInvalid or empty make file:                                          \u001b[31;40m\u001b[1m[error]\u001b[0m\n/data/code/profiles/express/express-current/patches.make\nfile_get_contents(/data/code/profiles/express/express-current/patches.make):\u001b[1;33;40m\u001b[1m[warning]\u001b[0m\nfailed to open stream: No such file or directory\nmake.utilities.inc:480\nInvalid or empty make file:                                          \u001b[31;40m\u001b[1m[error]\u001b[0m\n/data/code/profiles/express/express-current/patches.make", "stdout": "Project registry_rebuild contains 0 modules: .", "stdout_lines": ["Project registry_rebuild contains 0 modules: ."], "warnings": []}

**Comment by jwfuller** [comment]
Resolved
