### ISSUE TITLE
Vagrant up fails to mount d8.local

### ISSUE THREAD

**Issue by tommycox** [CuBoulder/express_local#59]
## Context

Vagrant hits an error when trying to mount d8.local, causing all further provisioning to fail/not start (inventory.local specifically).

## Process

1. `vagrant up`

## Expected result

Local vms provision without error.

## Current result

```
==> d8.local: Mounting NFS shared folders...
The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!

mount -o vers=3,udp,actimeo=2 192.168.33.1:/Users/thco6272/express_local/data/code /data/code
result=$?
if test $result -eq 0; then
if test -x /sbin/initctl && command -v /sbin/init && /sbin/init 2>/dev/null --version | grep upstart; then
/sbin/initctl emit --no-wait vagrant-mounted MOUNTPOINT=/data/code
fi
else
exit $result
fi


Stdout from the command:



Stderr from the command:

mount.nfs: access denied by server while mounting 192.168.33.1:/Users/thco6272/express_local/data/code
```

## Possible Fix

Comment out provisioning of d8.local in `Vagrantfile`.

----

## Links to Relevant

* [Slack Conversation](https://cu-boulder.slack.com/archives/dev/p1487182769000043)

**Comment by jwfuller** [comment]
What version of Vagrant, Ansible and Virtualbox are you running?

My current:
* Vagrant 1.8.6
* Ansible 2.1.2.0
* Virtualbox 5.1.6 r110634

**Comment by jwfuller** [comment]
Works on clean build and on re-provision
