### ISSUE TITLE
Install lil_shugger on inventory.local

### ISSUE THREAD

**Issue by kreynen** [CuBoulder/express_local#62]
## Context

I wrote the steps to configure on express.local, but it would be better to have this on everyone's inventory.local and get that deployed to the dev, test, and prod the same way.

**Comment by jwfuller** [comment]
Want to be able to develop, not just run

**Comment by jwfuller** [comment]
Unclear if development requires Node. Deferring to @alexfinnarn and @kreynen

Starting with running on the vm.
